#!/bin/sh

BANDWIDTH=56kbit
LATENCY=200msec
PACKET_LOSS=2%

tc qdisc del dev eth0 root 2> /dev/null

# 400ms ping, unlimited Mbps down, 0.05 Mbps up
tc qdisc add dev eth0 root handle 1:0 netem delay $LATENCY loss $PACKET_LOSS
tc qdisc add dev eth0 parent 1:1 handle 10: tbf rate $BANDWIDTH burst $BANDWIDTH latency $LATENCY
